services:
  # MySQL Database
  db:
    build: ./database
    container_name: mysql-db
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  swagger-ui: # For OpenAPI Documentation
    image: swaggerapi/swagger-ui
    ports:
      - "9090:8080"   # host:container
    volumes:
      - ./openapi:/usr/share/nginx/html/openapi
    environment:
      SWAGGER_JSON: /usr/share/nginx/html/openapi/api_documentation.yaml

volumes:
  mysql_data:
    name: mysql_data